#ifndef NDEBUG

#include "core/debug/TestReport.h"
#include "core/Logger.h"

#include <filesystem>
#include <fstream>
#include <format>

namespace debugpipeline {

    namespace {

        const char* StatusLabel(TestStatus status) {
            switch (status) {
                case TestStatus::Pass: return "PASS";
                case TestStatus::Warn: return "WARN";
                case TestStatus::Fail: return "FAIL";
                case TestStatus::Skip: return "SKIP";
            }
            return "UNKNOWN";
        }

        const char* SeverityLabel(uint32_t severity) {
            // VkDebugUtilsMessageSeverityFlagBitsEXT values (see ValidationMessageSink.h's own
            // comment for why this file avoids including <vulkan/vulkan.h> just for these).
            if (severity >= 0x1000) return "ERROR";
            if (severity >= 0x100)  return "WARNING";
            if (severity >= 0x10)   return "INFO";
            return "VERBOSE";
        }

        // Markdown pipe-table cells cannot contain a raw newline or '|' -- validation-layer
        // messages routinely contain both (multi-line VUID dumps). Collapse to a single line so
        // the summary table never breaks.
        std::string SanitizeForTableCell(const std::string& text, size_t maxLen = 160) {
            std::string out;
            out.reserve(text.size());
            for (char c : text) {
                if (c == '\n' || c == '\r') { out += ' '; }
                else if (c == '|') { out += "\\|"; }
                else { out += c; }
            }
            if (out.size() > maxLen) {
                out.resize(maxLen);
                out += "...";
            }
            return out;
        }

    } // namespace

    uint32_t TestReport::FailCount() const {
        uint32_t count = 0;
        for (const auto& result : m_Results) {
            if (result.status == TestStatus::Fail) { ++count; }
        }
        return count;
    }

    std::string TestReport::WriteMarkdown(const std::string& outputDir) const {
        std::error_code ec;
        std::filesystem::create_directories(outputDir, ec);
        if (ec) {
            LOG_ERROR(std::format("[TestReport] Failed to create output directory '{}': {}", outputDir, ec.message()));
            return {};
        }

        const std::string reportPath = outputDir + "/report.md";
        std::ofstream out(reportPath, std::ios::out | std::ios::trunc);
        if (!out.is_open()) {
            LOG_ERROR(std::format("[TestReport] Failed to open '{}' for writing.", reportPath));
            return {};
        }

        uint32_t passCount = 0, warnCount = 0, failCount = 0, skipCount = 0;
        for (const auto& result : m_Results) {
            switch (result.status) {
                case TestStatus::Pass: ++passCount; break;
                case TestStatus::Warn: ++warnCount; break;
                case TestStatus::Fail: ++failCount; break;
                case TestStatus::Skip: ++skipCount; break;
            }
        }

        // --- Header: everything an AI reading this report cold needs to know about the run's
        // context before looking at a single test result. ---
        out << "# DemoScene Engine -- Automated Debug/Validation Report\n\n";
        out << "This report was generated by `DebugTestPipeline` (src/core/debug/DebugTestPipeline.cpp), "
               "a Debug-only automated pass over the engine's rendering/precompute features. It is written "
               "to be diagnosable by an AI assistant with no access to the running engine: every FAIL section "
               "includes expected vs. actual values, raw Vulkan validation-layer messages, and a screenshot path "
               "where applicable.\n\n";

        out << "| Field | Value |\n";
        out << "|---|---|\n";
        out << "| Timestamp | " << m_Header.timestampIso8601 << " |\n";
        out << "| Git commit | " << m_Header.gitCommitHash << " |\n";
        out << "| Build config | " << m_Header.buildConfig << " |\n";
        out << "| GPU | " << m_Header.gpuName << " |\n";
        out << "| Driver | " << m_Header.driverVersionText << " |\n";
        out << "| Active EngineConfig preset | " << m_Header.activeConfigPreset << " |\n";
        out << "| Total tests | " << m_Results.size() << " |\n";
        out << "| Pass / Warn / Fail / Skip | " << passCount << " / " << warnCount << " / " << failCount << " / " << skipCount << " |\n\n";

        // --- Summary table: quick top-level scan before diving into any one section. ---
        out << "## Summary\n\n";
        out << "| # | Status | Feature | Frames | Actual (short) |\n";
        out << "|---|---|---|---|---|\n";
        for (size_t i = 0; i < m_Results.size(); ++i) {
            const auto& r = m_Results[i];
            out << "| " << (i + 1) << " | " << StatusLabel(r.status) << " | " << r.name << " | "
                << r.framesExecuted << " | " << SanitizeForTableCell(r.actual, 100) << " |\n";
        }
        out << "\n";

        // --- Detailed per-feature sections. ---
        out << "## Detailed Results\n\n";
        for (size_t i = 0; i < m_Results.size(); ++i) {
            const auto& r = m_Results[i];
            out << "### " << (i + 1) << ". [" << StatusLabel(r.status) << "] " << r.name << "\n\n";
            out << "- **Source:** `" << r.sourceFile << "`\n";
            out << "- **Frames executed:** " << r.framesExecuted << "\n";
            out << "- **Expected:** " << r.expected << "\n";
            out << "- **Actual:** " << r.actual << "\n";
            if (!r.screenshotPath.empty()) {
                out << "- **Screenshot:** `" << r.screenshotPath << "`\n";
            }
            if (!r.notes.empty()) {
                out << "- **Notes:** " << r.notes << "\n";
            }

            out << "- **Validation-layer messages during this test:** ";
            if (r.validationMessages.empty()) {
                out << "none\n";
            } else {
                out << r.validationMessages.size() << "\n\n";
                out << "  | Severity | Message |\n";
                out << "  |---|---|\n";
                for (const auto& msg : r.validationMessages) {
                    out << "  | " << SeverityLabel(msg.severity) << " | " << SanitizeForTableCell(msg.text) << " |\n";
                }
            }
            out << "\n";
        }

        out.close();
        LOG_INFO(std::format("[TestReport] Wrote report to '{}' ({} pass / {} warn / {} fail / {} skip).",
                              reportPath, passCount, warnCount, failCount, skipCount));
        return reportPath;
    }

}

#endif // NDEBUG
