#pragma once
// Phase PP2 (post-process stack roadmap -- see this repo's own project memory
// project_postprocess_stack_roadmap.md): Bloom, Lens Flare, Anamorphic Lens Flare, and Lens Dirt,
// all generated by one dual-filter mip chain pass -- see BloomDownsample.comp / BloomUpsample
// Composite.comp's own comments for the full technique (the same dual-filter approach presented in
// Call of Duty: Advanced Warfare's "Next Generation Post Processing" talk, which Unreal Engine's
// own non-FFT bloom path also approximates).
//
// --- Mip chain layout ---
// Two SEPARATE mip-chain images, `kMipCount` levels each (downsample) / `kMipCount - 1` levels
// (upsample) -- NOT one chain read-modify-written in place, because the upsample step's own tent
// filter samples texels neighboring the exact subresource it writes; reading and writing the same
// subresource in one dispatch (even at "different" texels) is an unsynchronized hazard with no
// portable barrier that fixes it mid-dispatch. Two chains sidestep this entirely: the downsample
// chain is written once, top to bottom, and only ever read afterward; the upsample chain is
// written once, bottom to top, reading the (already-finished) downsample chain's same-size mip
// plus its own smaller mip -- never its own same-size mip.
//
// --- Per-frame call order a caller must follow ---
//   1. RecordGenerate(cmd, hdrSourceView-already-visible-to-COMPUTE_SHADER-reads) -- records the
//      whole downsample chain (mip 0 = thresholded box-filter of `hdrSourceView`, mips 1..N-1 =
//      plain box-filter of the mip above), then the whole upsample chain (mip N-2 down to mip 0,
//      each = this mip's own downsample-chain detail + a tent-filtered upsample of the smaller
//      mip), with the mip-0 call additionally generating Lens Flare/Anamorphic Flare/Lens Dirt
//      (100% procedural, no texture asset for any of the three) and adding them on top.
//
// GetOutputView() (the upsample chain's own mip 0) is what renderer::PostProcessPass's composite
// shader samples and adds to the HDR scene color.

#include <cstdint>
#include <vector>
#include <vulkan/vulkan.h>
#include <vk_mem_alloc.h>
#include "renderer/vulkan/GpuImage.h"

namespace renderer {

    class BloomPass {
    public:
        BloomPass() = default;

        BloomPass(const BloomPass&) = delete;
        BloomPass& operator=(const BloomPass&) = delete;

        static constexpr VkFormat kFormat = VK_FORMAT_R16G16B16A16_SFLOAT;
        static constexpr uint32_t kMipCount = 6u;
        // Downsample chain mip used as the Lens Flare/Anamorphic Flare source -- small and already
        // heavily blurred (a wide, soft light source reads far more like real lens ghosting/streaks
        // than a sharp one), but not the very smallest mip (which would be too low-resolution for
        // the anamorphic streak's own horizontal taps to read as a coherent line).
        static constexpr uint32_t kFlareSourceMip = 3u;
        static_assert(kFlareSourceMip < kMipCount, "kFlareSourceMip must be a real mip of the downsample chain");

        struct Settings {
            float threshold = 1.0f;       // Bright-pass threshold, linear HDR luminance.
            float softKnee = 0.5f;
            float upsampleRadius = 1.0f;

            float ghostIntensity = 0.3f;
            uint32_t ghostCount = 4u;
            float ghostSpacing = 1.0f;

            float anamorphicIntensity = 0.15f;
            float anamorphicStretch = 0.10f; // UV-space half-width of the horizontal streak kernel.

            float dirtIntensity = 0.4f;
            float dirtScale = 6.0f;
        };

        // Mip 0 of the downsample chain is HALF `displayExtent` (matches renderer::HZBPass's own
        // "mip 0 is half source" convention) -- bloom/flares are inherently low-frequency, so full
        // display resolution would be pure wasted bandwidth.
        void Init(VkDevice device, VmaAllocator allocator, VkCommandPool commandPool, VkQueue queue,
            VkExtent2D displayExtent, VkImageView hdrSourceView);

        void Shutdown();

        // Recreates the downsample chain's own mip-0 descriptor binding when `hdrSourceView`'s
        // identity changes -- mirrors renderer::PostProcessPass::UpdateDescriptorSets' own reason
        // for existing (renderer::TAATSRPass's own output ping-pongs between 2 images every frame).
        void UpdateSourceDescriptor(VkImageView hdrSourceView);

        void RecordGenerate(VkCommandBuffer cmd, const Settings& settings);

        VkImageView GetOutputView() const { return m_UpsampleMipViews[0]; }

    private:
        struct DownsamplePushConstants {
            float outputTexelSizeX = 0.0f, outputTexelSizeY = 0.0f;
            float threshold = 0.0f;
            float softKnee = 0.0f;
            uint32_t isFirstMip = 0u;
        };

        struct UpsamplePushConstants {
            float outputTexelSizeX = 0.0f, outputTexelSizeY = 0.0f;
            float smallerMipTexelSizeX = 0.0f, smallerMipTexelSizeY = 0.0f;
            float upsampleRadius = 0.0f;
            uint32_t isFinalMip = 0u;
            float ghostIntensity = 0.0f;
            uint32_t ghostCount = 0u;
            float ghostSpacing = 0.0f;
            float anamorphicIntensity = 0.0f;
            float anamorphicStretch = 0.0f;
            float dirtIntensity = 0.0f;
            float dirtScale = 0.0f;
        };

        void BarrierAfterMipWrite(VkCommandBuffer cmd, VkImage image, uint32_t mipLevel) const;

        VkDevice m_Device = VK_NULL_HANDLE;
        VmaAllocator m_Allocator = VK_NULL_HANDLE;
        VkExtent2D m_DisplayExtent{ 0, 0 };

        GpuImage m_DownsampleImage;
        GpuImage m_UpsampleImage;
        std::vector<VkImageView> m_DownsampleMipViews; // Size kMipCount.
        std::vector<VkImageView> m_UpsampleMipViews;   // Size kMipCount - 1.
        std::vector<VkExtent2D> m_MipExtents;          // Size kMipCount, index-aligned with m_DownsampleMipViews.

        VkSampler m_LinearClampSampler = VK_NULL_HANDLE;

        VkDescriptorPool m_DescriptorPool = VK_NULL_HANDLE;

        VkDescriptorSetLayout m_DownsampleSetLayout = VK_NULL_HANDLE;
        std::vector<VkDescriptorSet> m_DownsampleSets; // Size kMipCount, index == mip level.
        VkPipelineLayout m_DownsamplePipelineLayout = VK_NULL_HANDLE;
        VkPipeline m_DownsamplePipeline = VK_NULL_HANDLE;

        VkDescriptorSetLayout m_UpsampleSetLayout = VK_NULL_HANDLE;
        std::vector<VkDescriptorSet> m_UpsampleSets; // Size kMipCount - 1, index == mip level.
        VkPipelineLayout m_UpsamplePipelineLayout = VK_NULL_HANDLE;
        VkPipeline m_UpsamplePipeline = VK_NULL_HANDLE;
    };

}
