#pragma once

// PCG framework roadmap, Phase 1 ("PCG Data Model"): typed handles/wrappers over this codebase's
// EXISTING spatial data sources -- Surface (a generated mesh/geometry entity), Volume (an AABB/OBB
// test region), Landscape (a reference into the existing GPU-driven procedural terrain), and Spline
// (the existing authored Hermite curve). UE5.8's PCG framework calls these "spatial data" types;
// each one there is a queryable data source a graph node samples POINTS from. This phase
// deliberately stops at the data-model layer -- these are lightweight, header-only reference/query
// types with NO sampler/spawner logic (that is a later phase's job); each wrapper's own comment
// below says exactly which existing subsystem it defers the actual heavy lifting to.

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <vector>

#include "core/maths/Maths.h"

namespace pcg {

    // ------------------------------------------------------------------------------------------
    // Surface: a reference to an existing procedurally-generated mesh/geometry entity.
    // ------------------------------------------------------------------------------------------
    // This engine's bindless GPU-driven pipeline identifies geometry by (meshID, materialID) --
    // see core/EntityData.h's EntityData struct and src/shaders/include/struct_custo.glsl's mirror
    // -- so a Surface reference is just that identifying pair plus the entity's world-space
    // placement offset (matching e.g. geom_terrain.comp's own Params.worldOffsetX/Y/Z convention).
    // NOT an owning mesh and NOT a mesh-sampling implementation: a future PCG "Get Surface Data"
    // node (Phase 3+, samplers) resolves this handle against the actual resident cluster/geometry
    // system (src/geometry/) to walk triangles/query a point-on-surface -- out of scope here.
    struct PcgSurfaceData {
        uint32_t meshID = 0;
        uint32_t materialID = 0;
        maths::vec3 worldOffset{ 0.0f, 0.0f, 0.0f };
    };

    // ------------------------------------------------------------------------------------------
    // Volume: an oriented bounding region (OBB; degenerates to a plain AABB when `orientation` is
    // left at its default identity quaternion) a future PCG density-filter/"Get Volume Data" node
    // can test points against.
    // ------------------------------------------------------------------------------------------
    struct PcgVolumeData {
        maths::vec3 center{ 0.0f, 0.0f, 0.0f };
        maths::vec3 halfExtents{ 0.5f, 0.5f, 0.5f };
        maths::quat orientation{}; // Identity by default -> axis-aligned (a plain AABB).

        // World-space point-in-volume test: rotates `worldPos` into this volume's local frame
        // (subtract center, then apply the INVERSE of `orientation` -- a unit quaternion's inverse
        // is its conjugate, (-x,-y,-z,w)) and checks each local axis against halfExtents. Correct
        // for both the AABB case (orientation == identity, RotateVector is then a no-op) and the
        // general OBB case.
        bool ContainsWorldPoint(const maths::vec3& worldPos) const {
            const maths::vec3 offset = worldPos - center;
            const maths::quat inverseOrientation{ -orientation.x, -orientation.y, -orientation.z, orientation.w };
            const maths::vec3 localPos = inverseOrientation.RotateVector(offset);

            return std::abs(localPos.x) <= halfExtents.x
                && std::abs(localPos.y) <= halfExtents.y
                && std::abs(localPos.z) <= halfExtents.z;
        }
    };

    // ------------------------------------------------------------------------------------------
    // Landscape: a reference into the existing GPU-driven procedural terrain heightfield.
    // ------------------------------------------------------------------------------------------
    // The terrain's actual height/normal sampling (fbm noise + river-channel blend) lives ENTIRELY
    // GPU-side (src/shaders/include/terrain_noise.glsl's SampleTerrainHeight, consumed by
    // src/shaders/src/PrimitiveGen/geom_terrain.comp at mesh-generation time; the per-pixel albedo
    // variant is src/shaders/include/terrain_shading.glsl's ComputeTerrainAlbedo) -- this codebase
    // has no CPU-side port of that noise function, since the terrain entity is generated by compute
    // shader, never touched by the CPU after its Params UBO is uploaded. This struct is therefore
    // deliberately just the REFERENCE/lookup-key data a future PCG "Get Landscape Data" sampler
    // node (Phase 3+) needs to identify which terrain patch and world-space region it should query
    // -- fields mirror geom_terrain.comp's own Params UBO layout so a future CPU-side terrain query
    // (should one ever be added, e.g. for bake-time point generation) has an unambiguous mapping
    // back to the GPU generation parameters. Porting SampleTerrainHeight itself to the CPU is
    // explicitly out of scope for this phase.
    struct PcgLandscapeData {
        uint32_t meshID = 0;               // Matches geom_terrain.comp's Params.meshID.
        maths::vec3 worldOffset{ 0.0f, 0.0f, 0.0f }; // Matches Params.worldOffsetX/Y/Z.
        float width = 0.0f;                // Matches Params.width (world-space X extent).
        float length = 0.0f;               // Matches Params.length_ (world-space Z extent).
    };

    // ------------------------------------------------------------------------------------------
    // Spline: a CPU-usable wrapper around this codebase's EXISTING authored Hermite curve
    // representation (src/shaders/include/spline_deformation.glsl's SplineControlPoint / Hermite
    // basis), so a future PCG "Get Spline Data" sampler node (Phase 3+) can evaluate positions/
    // tangents along an authored curve without a GPU roundtrip.
    // ------------------------------------------------------------------------------------------
    // The Hermite math below (PcgSplineControlPoint, HermiteEvaluateCPU, EvaluatePosition/Tangent)
    // is NOT a new spline formulation -- it reproduces spline_deformation.glsl's own
    // HermiteEvaluate/ApplySplineDeformation exactly (same cubic Hermite basis functions, same
    // "vec3 position + vec3 tangent" control-point representation, same global-parameter-to-
    // segment-index mapping). renderer::ClusterRenderPipeline.cpp already contains an equivalent
    // CPU mirror (HermiteEvaluateCPU/ApplySplineDeformationCPU, used by its own
    // ValidateSplineBounds() startup check) proving this exact CPU-port technique is this
    // codebase's established, accepted way to keep a GPU curve algorithm available on the CPU --
    // but that copy lives in an anonymous namespace private to ClusterRenderPipeline.cpp, so it is
    // not reachable from here. Re-deriving it as this phase's own header-exposed, reusable version
    // (rather than touching ClusterRenderPipeline.cpp, which is out of this phase's scope) is a
    // faithful port of the SAME published formula, not an invented alternative.
    struct PcgSplineControlPoint {
        maths::vec3 position{ 0.0f, 0.0f, 0.0f };
        maths::vec3 tangent{ 0.0f, 0.0f, 1.0f };
    };

    class PcgSplineData {
    public:
        explicit PcgSplineData(std::vector<PcgSplineControlPoint> controlPoints)
            : m_ControlPoints(std::move(controlPoints)) {
        }

        size_t ControlPointCount() const { return m_ControlPoints.size(); }
        const std::vector<PcgSplineControlPoint>& ControlPoints() const { return m_ControlPoints; }

        // Evaluates the curve's world-space position at global parameter `t`, where t in
        // [0, ControlPointCount() - 1] (matching spline_deformation.glsl's ApplySplineDeformation's
        // own globalT convention: integer values of t land exactly on a control point, fractional
        // values interpolate within the segment [floor(t), floor(t)+1]).
        maths::vec3 EvaluatePosition(float t) const {
            maths::vec3 position, tangent;
            EvaluateSegment(t, position, tangent);
            return position;
        }

        // Evaluates the curve's (un-normalized, magnitude not meaningful -- only direction is)
        // tangent at global parameter `t`, same convention as EvaluatePosition.
        maths::vec3 EvaluateTangent(float t) const {
            maths::vec3 position, tangent;
            EvaluateSegment(t, position, tangent);
            return tangent;
        }

    private:
        // Cubic Hermite basis, evaluated at a two-endpoint segment (p0/t0 at u=0, p1/t1 at u=1) --
        // byte-for-byte the same basis functions as spline_deformation.glsl's HermiteEvaluate.
        static void HermiteEvaluateCPU(const maths::vec3& p0, const maths::vec3& t0, const maths::vec3& p1, const maths::vec3& t1,
            float u, maths::vec3& outPosition, maths::vec3& outTangent) {
            const float u2 = u * u;
            const float u3 = u2 * u;

            const float h00 = 2.0f * u3 - 3.0f * u2 + 1.0f;
            const float h10 = u3 - 2.0f * u2 + u;
            const float h01 = -2.0f * u3 + 3.0f * u2;
            const float h11 = u3 - u2;
            outPosition = p0 * h00 + t0 * h10 + p1 * h01 + t1 * h11;

            const float dh00 = 6.0f * u2 - 6.0f * u;
            const float dh10 = 3.0f * u2 - 4.0f * u + 1.0f;
            const float dh01 = -6.0f * u2 + 6.0f * u;
            const float dh11 = 3.0f * u2 - 2.0f * u;
            outTangent = p0 * dh00 + t0 * dh10 + p1 * dh01 + t1 * dh11;
        }

        void EvaluateSegment(float t, maths::vec3& outPosition, maths::vec3& outTangent) const {
            const size_t count = m_ControlPoints.size();
            if (count == 0) {
                outPosition = maths::vec3{ 0.0f, 0.0f, 0.0f };
                outTangent = maths::vec3{ 0.0f, 0.0f, 1.0f };
                return;
            }
            if (count == 1) {
                outPosition = m_ControlPoints[0].position;
                outTangent = m_ControlPoints[0].tangent;
                return;
            }

            const float maxT = static_cast<float>(count - 1);
            const float clampedT = std::clamp(t, 0.0f, maxT);

            int segmentIndex = static_cast<int>(std::floor(clampedT));
            segmentIndex = std::clamp(segmentIndex, 0, static_cast<int>(count) - 2);
            const float localU = clampedT - static_cast<float>(segmentIndex);

            const PcgSplineControlPoint& c0 = m_ControlPoints[static_cast<size_t>(segmentIndex)];
            const PcgSplineControlPoint& c1 = m_ControlPoints[static_cast<size_t>(segmentIndex) + 1];
            HermiteEvaluateCPU(c0.position, c0.tangent, c1.position, c1.tangent, localU, outPosition, outTangent);
        }

        std::vector<PcgSplineControlPoint> m_ControlPoints;
    };

}
